apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime-version: '1.0'
  name: {{ .Values.app.name }}
spec:
  ports:
  - name: {{ .Values.runtime.portName }}
    protocol: TCP
    port: {{ .Values.runtime.servicePort }}
    targetPort: {{ .Values.runtime.containerPort }}
  selector:
    app: {{ .Values.app.name }}
    deployment: {{ .Values.app.name }}
